version: "3.4"

services:
  db:
    image: orientdb:2.2.30
    environment:
      ORIENTDB_ROOT_PASSWORD: shitsuji
    volumes:
      - db_config:/orientdb/config
      - db_data:/orientdb/databases
      - db_backup:/orientdb/backup
  app:
    image: shitsuji/shitsuji-api
    depends_on:
      - db
    volumes:
      - shitsuji_storage:/shitsuji/storage
    environment:
      # location of config file for the api itself
      # SHITSUJI_CONFIG_FILE:
      # path where the repositories are going to be saved - absolute path!
      SHITSUJI_CONFIG_STORAGE_PATH: /shitsuji/storage
      # secret phrase used to generate hash of password
      # SHITSUJI_CONFIG_SECRET:
      # location of config file, together with name of the file in you projects
      # SHITSUJI_REPOSITORY_CONFIG_FILE_PATH:
      ORIENTDB_HOST: db
      # ORIENTDB_PORT:
      # ORIENTDB_USER:
      # ORIENTDB_PASSWORD:
      ORIENTDB_DB_NAME: test
      ORIENTDB_DB_USER: root
      ORIENTDB_DB_PASSWORD: shitsuji
  proxy:
    image: shitsuji/shitsuji-proxy
    ports:
      - "5000:443"
    secrets:
      - proxy_cert
      - proxy_dhparam
      - proxy_key
    environment:
      PROXY_HOST: app
      PROXY_PORT: 5000
  ui:
    image: shitsuji/shitsuji-ui
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - proxy_cert
      - proxy_dhparam
      - proxy_key
    environment:
      API_HOST: https://localhost
      API_PORT: 5000

secrets:
  proxy_cert:
    file: ./secrets/cert.crt
  proxy_dhparam:
    file: ./secrets/dhparam.pem
  proxy_key:
    file: ./secrets/key.pem

volumes:
  db_config:
  db_data:
  db_backup:
  shitsuji_storage: